### ISSUE TITLE
song history quick edit not working

### ISSUE THREAD

**Issue by ArranLH** [radiopanel/radiopanel#14] opened 2021-06-11 13:54 UTC
**Describe the bug**
In cloud hosted- a pencil appears on song history to quickly correct any metadata. Self hosted it seems might still have some code to check for the feature to be enabled, thus does not work.

**Comment by HybridFox** [comment] 2021-06-11 13:55
Duplicate of #8 should be fixed in latest version 0.0.1-alpha.15

**Closed by HybridFox** 2021-06-11 13:55 UTC
